FROM pytorch/pytorch:2.6.0-cuda12.6-cudnn9-devel AS builder

RUN apt-get update \
	&& apt-get install -y git ca-certificates \
	&& rm -rf /var/lib/apt/lists/*

ENV CUDA_DOCKER_ARCH=all
ENV GGML_CUDA=1
ENV CMAKE_ARGS="-DGGML_CUDA=on"

COPY requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /app/wheels -r requirements.txt

FROM pytorch/pytorch:2.6.0-cuda12.6-cudnn9-runtime
WORKDIR /app

COPY --from=builder /app/wheels /wheels
RUN pip install --no-cache-dir /wheels/* && rm -rf /wheels

ENV LD_LIBRARY_PATH="/opt/conda/lib/python3.11/site-packages/nvidia/cuda_runtime/lib/:${LD_LIBRARY_PATH}"
ENV LD_LIBRARY_PATH="/opt/conda/lib/python3.11/site-packages/nvidia/cublas/lib/:${LD_LIBRARY_PATH}"

COPY app.py .

EXPOSE 7860
CMD ["python3", "app.py"]
