name: Build and Push Docker (CPU & CUDA)

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Images selection (cpu, cuda, both)"
        required: true
        default: "both"

permissions:
  contents: write
  packages: write

jobs:
  docker:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push CPU image
        if: ${{ github.event.inputs.target == 'cpu' || github.event.inputs.target == 'both' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-cpu
          push: true
          pull: true
          platforms: linux/amd64
          tags: |
            ghcr.io/sergey21000/gradio-llamacpp-chatbot-cpu:latest
            ghcr.io/sergey21000/gradio-llamacpp-chatbot-cpu:${{ github.sha }}

      - name: Build and push CUDA image
        if: ${{ github.event.inputs.target == 'cuda' || github.event.inputs.target == 'both' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-cuda
          push: true
          pull: true
          platforms: linux/amd64
          tags: |
            ghcr.io/sergey21000/gradio-llamacpp-chatbot-cuda:latest
            ghcr.io/sergey21000/gradio-llamacpp-chatbot-cuda:${{ github.sha }}
