name: Deploy to HuggingFace Spaces

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Deploy to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface.co/spaces/${{ github.repository }}
          cd ${{ github.event.repository.name }}
          
          cp ../hf-spaces-deploy/Dockerfile .
          cp ../hf-spaces-deploy/config.py .
          
          git add .
          git commit -m "Auto-deploy from GitHub Actions: ${{ github.sha }}" || echo "No changes to commit"

          git push https://${{ github.repository_owner }}:$HF_TOKEN@huggingface.co/spaces/${{ github.repository }} main
